# Generated by Django 2.2 on 2020-11-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopHotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('piso', models.IntegerField()),
            ],
        ),
    ]
