# Generated by Django 2.2 on 2020-11-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TopHotel', '0002_habitacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Habitacion',
        ),
    ]
